server:
  port: 8083
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Kanban
  application:
    name: user-team
eureka:
  client:
    serverUrl:
    defaultZone: http://localhost:8761
    fetchRegistry: true
    registerWithEureka: true
  instance:
    hostname: localhost