server:
  port: 8084
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/KanbanNew
  application:
    name: user-notification
eureka:
  client:
    serverUrl:
    defaultZone: http://localhost:8761
    fetchRegistry: true
    registerWithEureka: true
  instance:
    hostname: localhost